version: '3'

services:
  web:
    build: .
    command: uwsgi --http 0.0.0.0:8000 --module appsubscriptiondashboard.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: appsubscriptiondashboard
      MYSQL_USER: AppSubDashboard
      MYSQL_PASSWORD: AppSubscription@123$$
      MYSQL_ROOT_PASSWORD: App@123$$
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
