# Generated by Django 3.2.7 on 2024-03-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appactionanalytics',
            name='search_params',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
