# Generated by Django 3.2.7 on 2024-03-17 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('subscription_plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('subscription_plan_name', models.CharField(max_length=100)),
                ('subscription_plan_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': 'subscription_plan',
                'ordering': ['subscription_plan_price'],
            },
        ),
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('app_name', models.CharField(blank=True, default=None, max_length=150, null=True, unique=True)),
                ('app_description', models.TextField(blank=True, default=None, null=True)),
                ('app_owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_app',
                'ordering': ['app_name'],
            },
        ),
        migrations.CreateModel(
            name='UserAppSubscription',
            fields=[
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('subscription_app', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptionapp.userapp')),
                ('subscription_plan', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptionapp.subscriptionplan')),
                ('subscription_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_subscriptions',
                'ordering': ['-subscription_id'],
            },
        ),
    ]
