# Generated by Django 3.2.7 on 2024-03-20 06:31

from django.db import migrations, models
import subscriptionapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='app_no',
            field=models.CharField(blank=True, db_index=True, default=subscriptionapp.models.UserApp.get_app_no, max_length=50, null=True),
        ),
    ]
