# Generated by Django 3.2.7 on 2024-03-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionapp', '0002_userapp_app_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='subscription_plan_no',
            field=models.CharField(blank=True, db_index=True, default='SubPlan-GIPQeczg3k9jU2BnI2onzzmx', max_length=50, null=True),
        ),
    ]
