# Generated by Django 3.2.7 on 2024-03-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionapp', '0003_subscriptionplan_subscription_plan_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappsubscription',
            name='subscription_no',
            field=models.CharField(blank=True, db_index=True, default='AppSub-iBEyQ2Zjb6JPpNtZcELPTvvk', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='subscription_plan_no',
            field=models.CharField(blank=True, db_index=True, default='SubPlan-tT7RqCa3hgHFTFF6HlLQKmG5', max_length=50, null=True),
        ),
    ]
